services:
  - type: web
    name: multilingual-video-workflow
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: CLAUDE_API_KEY  
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: WAV2LIP_API_KEY
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET_NAME
        sync: false
      - key: R2_ENDPOINT_URL
        sync: false
      - key: R2_PUBLIC_URL
        sync: false
      - key: PORT
        value: 10000